### ISSUE TITLE
Loop when the filament runout sensor is activated or print is paused

### ISSUE THREAD

**Issue by RoCkHeLuCk** [jounathaen/octoprint_btt_touch_support#2] opened 2024-11-27 21:40 UTC
First, I would like to thank you for developing such a great tool. It works wonderfully.

I am using "Orca Slicer 2.2" for slicing, a "TFT 24" display, and "Marlin-2.1.2.4", the latest version of OctoPrint.

I started using this plugin today, and due to an unforeseen event (my cat), the filament broke, activating the filament break sensor. The message appeared on both the display and OctoPrint, allowing me to choose to purge and disable the filament. However, after this, the process of pausing and resuming the print enters a loop. I can only access the stop button on the display, and in OctoPrint, there is a significant delay, and everything becomes disabled.

I tried pausing the printer, and when I resumed, it fell into the same loop. It seems that the display and OctoPrint are not in sync. I tested everything without this plugin, and it worked without any issues.

**Comment by jounathaen** [comment] 2024-11-30 09:47
Hi and thanks for the feedback!
I tried to reproduce your unforeseen event (I think I got close, despite not having a cat :wink: ), but it worked on my machine.

- Maybe you could ask your cat to reproduce such an event and post the terminal output here?
- Also, can you check that the relevant _GCODE Scripts_ in OctoPrint are empty (5th section in the settings)?

> The message appeared on both the display and OctoPrint, allowing me to choose to purge and disable the filament.

Once I inserted new filament, the "Disable Filament Runout" button changed to "Continue". Was this the case for you as well?

> However, after this, the process of pausing and resuming the print enters a loop. I can only access the stop button on the display, and in OctoPrint, there is a significant delay, and everything becomes disabled.

Maybe this could be caused by this plugin sending the relevant action commands to all serial ports, and thus octoprint receiving the action notifications it had just sent itself :thinking: 
This is definitely something that could be improved.

**Comment by jounathaen** [comment] 2024-11-30 13:47
I've created a new release (v0.2.0) that allows you to specify the TFT's serial port. There is a good chance, that this fixes the issue :slightly_smiling_face:

**Comment by RoCkHeLuCk** [comment] 2024-12-01 14:41
Thanks for your help and prompt response, and sorry for the delay in replying.
If it's because you don't have a cat, borrow one 😉.

**Your Question: Maybe you could ask your cat to reproduce such an event and post the terminal output here?
Also, can you check if the relevant GCODE scripts in OctoPrint are empty (5th section in the settings)?**
My Answer: I don't quite understand what you mean, start, pause, filament change, end macros? If so, I use the "M300 Player" plugin to liven things up.

**Your Question: Did the message appear on the display and in OctoPrint, allowing me to choose to purge and disable the filament?**
My Answer: Yes, on the display and in OctoPrint.

**Your Question: After I inserted the new filament, the "Disable filament runout" button changed to "Continue". Was this the case for you too?**
My Answer: Yes, on the display and in OctoPrint.

**Your Question: Question: However, after that, the process of pausing and resuming printing goes into a loop. I can only access the stop button on the display, and in OctoPrint there is a significant delay and everything is disabled.**
My Answer: Yes, you can see that the display and octoprint are fighting, one pauses and the other unpauses, but it only happens with this plugin. Without it, the message appears on both but it doesn't go into a loop.

*Your: Maybe this could be caused by this plugin sending the relevant action commands to all serial ports and therefore octoprint receiving the action notifications that it had sent itself 🤔
This is definitely something that could be improved.
I created a new version (v0.2.0) that allows you to specify the serial port of the TFT. There is a good chance that this will fix the problem 🙂**
My Answer: my Octoprint and TFT are connected directly to the SKR 1.4, Marlin Serial -1 and Serial 0, I will test this new version and reproduce the occurrence again and give you feedback.

**Comment by jounathaen** [comment] 2024-12-01 14:54
Looking forward to your feedback! 
Just to avoid confusion: The `-1` and `0` you mention is the hardware's enumeration. Marlin numbers them independently of the hardware to `1` and `2`, depending on your Marlin configuration (e.g., in `Configuration.h`: ` #define SERIAL_PORT_2 -1` makes hardware serial port -1 the second serial port). 
When you type `M118 P1 E1 Hello there` in the terminal tab in OctoPrint and you see "Hello there" on the TFT's main screen, it is connected to port 1. If that doesn't work, try `M118 P2 E1 Hello there`, then it is port 2.

**Comment by RoCkHeLuCk** [comment] 2024-12-01 23:11
In Marlin it is like this:
#define SERIAL_PORT -1
#define SERIAL_PORT_2 0

So the TFT works like this:
M118 P2 E1 Hello

I saw that you put an option to choose the port, very good, I think you should put this command in the comments to help others find out which port the TFT is on.
But since technology is never easy, it doesn't matter if I put 0, 1, 2, 3... now none of the benefits of this plugin work with the TFT, as if it were not installed. Everything works normally as before, without the benefit.

I would like to try to help you with the development, but I confess that I don't know anything about Python and much less about the Octoprint plugin, but I would like to learn.

**Comment by jounathaen** [comment] 2024-12-02 08:44
Ok, so it definitely must be port 2 then in this plugin's settings. Quite strange that it doesn't work with this setting on your setup. :thinking: 
Could you maybe send me some a log from an OctoPrint run?

- Go to Settings → Serial-Connection → Serial Logging and activate _Log communication to serial.log_
- Go to Settings → Logging → Logging Levels and select _octoprint.plugsin.btt_touch_support_. It should get added to a list above with _DEBUG_ level selected
- Go to Settings → Logging → Logs and delete _octoprint.log_ and _serial.log_ with the trash icon.
- Start a print
- challenge your cat
- Go to Settings → Logging → Logs and download _serial.log_ and _octoprint.log_. (Check the files for potentially sensitive information) and then upload them here.
- Go to Settings → Serial-Connection → Serial Logging and **de-** activate _Log communication to serial.log_

**Comment by RoCkHeLuCk** [comment] 2024-12-07 16:49
Sorry for the delay, the end of the year is always a rush.

Today I did what you asked me to do, step by step, everything worked correctly, the TFT worked perfectly synchronized with the Octoprint, pause, play and Filament Runout without loop. Your fix really fixed it :)
I did some tests to find out why it didn't work before, I discovered that if you change the channel from 0 to 1, 2... whatever, you have to restart the Octoprint for it to work, otherwise the communication between them doesn't work.

In addition to adding the M118 instruction to help locate the TFT channel, I suggest requesting the Octoprint restart, for it to take effect.

This plugin is very good now synchronizing the two screens.

I use the M300 compositiions to liven things up, I had to install a buzzer on the SKR to hear the touches, because the TFT doesn't receive such a command, do you think it's possible to add support to this plugin to redirect the M300 command to the TFT. From the forums I visited, there are many people who install an add-on. If you find it interesting, create an issue for that, let's go.

**Comment by jounathaen** [comment] 2024-12-09 09:50
Very nice to hear that it works for you. I'm a little surprised, that you didn't get a notification with a restart reminder when updating this plugin because I do. That is an OctoPrint feature, so I think this is out of scope for this plugin.

Regarding your M300 suggestion: According to [the firmware documentation](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware?tab=readme-ov-file#printing-from-host), you can play a tone with the following G-Code: `M300 TFT [P<ms>] [S<Hz>]` (with added `TFT`). Unfortunately, I cannot test this as I removed the speaker from my display. I'm also not sure if and how this plugin should handle this situation?

- If the user utilizes `M300` in their start/end/filament-change/filament-runout g-code, they could just insert `M300 TFT` instead. → no action required by this plugin
- This plugin could intercept all `M300` g-codes and replace them with `M300 TFT`.
- I don't know how _M300Player_ works and what it even does, so I cannot really say what the best interaction would be.

Anyway, if you can confirm if the above g-code works, I'll think about what to do.

**Closed as completed** 2024-12-09 10:01 UTC
